name: truxify_driver
description: Driver-side Truxify web Flutter app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  google_fonts: ^8.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
