import express from 'express';
import { z } from 'zod';
import { supabase } from '../config/db.js';
import { authenticate, requireRole } from '../middleware/auth.js';

const router = express.Router();

// ============================================================================
// 🛡️ OFFLINE SYNC VALIDATION SCHEMAS (ISSUE #362)
// ============================================================================

// Schema for an individual Trip Event from the Flutter offline database
const tripEventSchema = z.object({
  id: z.string().min(1, "Event ID is required"),
  trip_id: z.string().optional().nullable(),
  type: z.string().min(1, "Event type is required"),
  occurred_at: z.string().datetime("occurred_at must be a valid ISO 8601 date string"),
  // Allow flexible metadata payloads (like speed, battery level, etc.)
  payload: z.record(z.any()).optional().default({}),
  // Tracking the retry count sent by the Flutter SyncEngine
  retry_count: z.number().int().nonnegative().optional().default(0)
});

// Schema for the Batch Payload generated by apps/customer/.../sync_engine.dart
const batchSyncSchema = z.object({
  events: z.array(tripEventSchema).max(100, "Maximum batch size exceeded (Limit: 100)"),
  idempotencyKey: z.string().min(1, "Idempotency key is required to prevent duplicates")
});

// Reusable Middleware for validating the batch payload
const validateBatchPayload = (schema) => (req, res, next) => {
  try {
    req.body = schema.parse(req.body);
    next();
  } catch (error) {
    if (error instanceof z.ZodError) {
      const formattedErrors = (error.issues || error.errors).map(err => ({
        field: err.path.join('.'),
        message: err.message
      }));
      // The Flutter app explicitly looks for 422 to stop retrying bad payloads
      return res.status(422).json({
        error: 'Unprocessable Entity: Malformed batch payload',
        details: formattedErrors
      });
    }
    next(error);
  }
};

// ============================================================================
// 📡 OFFLINE SYNC ENDPOINT: BATCH EVENT INGESTION
// ============================================================================

/**
 * POST /api/v1/trips/events/batch
 * Handles batched telemetry and trip events uploaded by the mobile client
 * after recovering from network loss.
 */
router.post('/events/batch', authenticate, validateBatchPayload(batchSyncSchema), async (req, res) => {
  const { events, idempotencyKey } = req.body;
  const userId = req.user.id;

  if (events.length === 0) {
    // Flutter expects 200 or 202 for success.
    return res.status(200).json({ message: 'Empty batch received, nothing to process.' });
  }

  try {
    // 1. Check Idempotency (Prevent double processing)
    // We check if this exact batch has already been processed recently.
    const { data: existingBatch } = await supabase
      .from('processed_batches')
      .select('id')
      .eq('idempotency_key', idempotencyKey)
      .maybeSingle();

    if (existingBatch) {
      console.log(`[SyncEngine] Ignored duplicate batch: ${idempotencyKey}`);
      // Return 202 Accepted so the Flutter app marks them as synced locally
      return res.status(202).json({ message: 'Batch already processed.' });
    }

    // 2. Prepare data for bulk upsert
    // We map the validated Zod objects to match the database column names
    const recordsToInsert = events.map(event => {
      const lat = event.payload?.lat !== undefined ? Number(event.payload.lat) : null;
      const lng = event.payload?.lng !== undefined ? Number(event.payload.lng) : null;

      return {
        event_id: event.id,
        user_id: userId,
        trip_id: event.trip_id || null,
        event_type: event.type,
        event_timestamp: event.occurred_at,
        latitude: lat,
        longitude: lng,
        metadata: event.payload,
        created_at: new Date().toISOString()
      };
    });

    // 3. Bulk Insert / Upsert into the trip_events table
    // Upsert ensures that if a specific event ID already exists, it just updates it
    // rather than failing the whole batch.
    const { error: insertError } = await supabase
      .from('trip_events')
      .upsert(recordsToInsert, { onConflict: 'event_id' });

    if (insertError) {
      console.error('[SyncEngine] Bulk Insert Failed:', insertError.message);
      // Return 500 so the Flutter app knows to apply exponential backoff and retry later
      return res.status(500).json({ error: 'Database failed to process batch.' });
    }

    // 4. Log the successful batch using the idempotency key
    // This prevents the same batch from being uploaded again if the client crashes
    // before it can mark them as synced in its local SQLite db.
    const { error: idempotencyError } = await supabase
      .from('processed_batches')
      .insert({
        idempotency_key: idempotencyKey,
        user_id: userId,
        event_count: events.length,
        processed_at: new Date().toISOString()
      });

    if (idempotencyError) {
      // Non-fatal error. We processed the events, but failed to log the key.
      console.warn(`[SyncEngine] Failed to log idempotency key: ${idempotencyKey}`);
    }

    // 5. Respond with 202 Accepted
    // This triggers `return true;` in the Flutter SyncEngine, allowing it to
    // clear the local database queue.
    console.log(`[SyncEngine] Successfully processed batch of ${events.length} events for User: ${userId}`);
    return res.status(202).json({
      message: 'Batch processed successfully',
      processed_count: events.length
    });

  } catch (err) {
    console.error('[SyncEngine] Critical processing error:', err.message);
    // 500 triggers the `_backoffDelay` in the Flutter app
    return res.status(500).json({ error: 'Internal server error during batch processing.' });
  }
});

// ============================================================================
// 🚀 ADDITIONAL TRIP ROUTES CAN BE ADDED BELOW
// ============================================================================

export default router;