name: truxify
description: Truxify customer-side mock Flutter app.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  flutter_map: ^8.3.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  http: ^1.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0
  uuid: ^4.2.2
  geocoding: ^4.0.0
  geolocator: ^10.1.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true